require('../src/assets/styles/index.scss');
require('./index.scss');

import {default as TemplateStories} from './template';
// import AvatarStories from './avatar';
// import ButtonStories from './button';
// import CardStories from './card';
// import CheckboxStories from './checkbox';
// import CollapseStories from './collapse';
// import DatePickerStories from './datepicker';
// import DialogStories from './dialog';
// import DropdownStories from './dropdown';
// import GridStories from './grid';
// import InputStories from './input';
// import ListStories from './list';
// import MenuStories from './menu';
// import MessageStories from './message';
// import PaginationStories from './pagination';
// import ProgressStories from './progress';
// import RadioStories from './radio';
// import SpinnerStories from './spinner';
// import SwitchStories from './switch';
// import TooltipStories from './tooltip';
// import TableStories from './table';
// import UploadStories from './upload';
// import StepsStories from './steps';
// import TabsStories from './tab-bar';
// import SelectStories from './select';
// import CheckSort from './check-sort';

// biz components
// import EcoScoreStories from './eco-score';
// import SummaryStories from './summary';
// import TreeStories from './tree';
// import DateTimeRanegPickerStories from './date-time-range-picker';
// import HeaderStories from './header';
// import OverviewListStories from './overview-list';
// import CardTableStories from './card-table';
// import FuelBarChartStories from './fuel-bar-chart';
// import LayoutStories from './layout';
// import ImportStories from './import';
// import InputSelectStories from './input-select';
// import ActionTableStories from './action-table';
// import MonthRangePickerStories from './month-range-picker';
// import TransferStories from './transfer';

TemplateStories();
// AvatarStories();
// ButtonStories();
// CardStories();
// CheckboxStories();
// CollapseStories();
// DatePickerStories();
// DialogStories();
// DropdownStories();
// GridStories();
// InputStories();
// ListStories();
// MenuStories();
// MessageStories();
// PaginationStories();
// ProgressStories();
// RadioStories();
// SpinnerStories();
// SwitchStories();
// TableStories();
// TooltipStories();
// UploadStories();
// StepsStories();
// TabsStories();
// SelectStories();
// CheckSort();

// CardTableStories();
// DateTimeRanegPickerStories();
// MonthRangePickerStories();
// EcoScoreStories();
// FuelBarChartStories();
// HeaderStories();
// OverviewListStories();
// SummaryStories();
// TreeStories();
// LayoutStories();
// ImportStories();
// InputSelectStories();
// ActionTableStories();
// TransferStories();